name: Release browser tracker
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Remove functions
        run: rm -rf functions
      - name: Transpiler tracker
        run: npm run ci:tracker:build
      - name: Push to 'release' branch so we can use it on jsdelivr
        run: |
          git config --global user.email "hugo@keel.xyz"
          git config --global user.name "Auto Release"
          git switch -c release
          rm .gitignore
          git add .gitignore
          git add tracker.js
          git commit -m "Add tracker.js"
          git push --force origin release
